### PR TITLE
handling rate exceeded messages

### PR DESCRIPTION
**Pull request by silarsis**
We're using this to do multiple stack deployments at once from a single server, and running into AWS rate limiting. This is the recommended fix as per http://docs.aws.amazon.com/general/latest/gr/api-retries.html - tested and confirmed working for us.

### CODE REVIEW

**Comment by omribahumi** [comment]
Thanks for the contribution!

I think it'll be much simpler to offload the retry logic to another function, so instead of

``` python
stack = self.describe_stack(name)
```

You'd use

``` python
stack = boto_retry(self.desctibe_stack, name)
```

**Comment by silarsis** [comment]
Absolutely - it's only done this way so I'm not madly refactoring in ways
you might not like, and because I didn't have time for more than a quick
fix/demonstration of the issue

On Monday, 15 June 2015, Omri Bahumi notifications@github.com wrote:

> Thanks for the contribution!
> 
> I think it'll be much simpler to offload the retry logic to another
> function, so instead of
> 
> stack = self.describe_stack(name)
> 
> You'd use
> 
> stack = boto_retry(self.desctibe_stack, name)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EverythingMe/rainbow/pull/29#issuecomment-111975406.

## 

Sent from Gmail Mobile

**Comment by omribahumi** [comment]
Actually, retries should be handled in boto. I think that you're hitting this error since you're running rainbow multiple times, and boto loses retry context (increasing the backoff delay or something similar).

Aparently, the number of retries can be tuned with the boto config file. See http://boto.readthedocs.org/en/latest/boto_config_tut.html (`num_retries` in particular)

Tell me if this solves your problem

**Comment by omribahumi** [comment]
And the code is here
https://github.com/boto/boto/blob/2d7796a625f9596cbadb7d00c0198e5ed84631ed/boto/utils.py#L198

**Comment by omribahumi** [comment]
@silarsis I don't understand. Can't you tune the `num_retries` boto.cfg value?

**Comment by silarsis** [comment]
Sorry, forgot the PR was still open. num_retries might be the right answer, I looked at it briefly and it looked like it was limiting the number of retries rather than controlling the backoff, but I can see now if I just set it really high I'll probably achieve fundamentally the same thing. Will test and see, and re-open PR if it doesn't work.

**Pull request closed without merging**
